# Alpha environment overrides (local MicroK8s)
namespace: gough
replicaCount: 1
image:
  pullPolicy: Never
env:
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: RELEASE_MODE
    value: "false"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: gough.localhost.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscaling:
  enabled: false
