// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gough/capacity.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Capacity_Forecast_FullMethodName = "/gough.v1.Capacity/Forecast"
	Capacity_Risks_FullMethodName    = "/gough.v1.Capacity/Risks"
)

// CapacityClient is the client API for Capacity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CapacityClient interface {
	Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResponse, error)
	Risks(ctx context.Context, in *RisksRequest, opts ...grpc.CallOption) (*RisksResponse, error)
}

type capacityClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityClient(cc grpc.ClientConnInterface) CapacityClient {
	return &capacityClient{cc}
}

func (c *capacityClient) Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastResponse)
	err := c.cc.Invoke(ctx, Capacity_Forecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityClient) Risks(ctx context.Context, in *RisksRequest, opts ...grpc.CallOption) (*RisksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RisksResponse)
	err := c.cc.Invoke(ctx, Capacity_Risks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityServer is the server API for Capacity service.
// All implementations must embed UnimplementedCapacityServer
// for forward compatibility.
type CapacityServer interface {
	Forecast(context.Context, *ForecastRequest) (*ForecastResponse, error)
	Risks(context.Context, *RisksRequest) (*RisksResponse, error)
	mustEmbedUnimplementedCapacityServer()
}

// UnimplementedCapacityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapacityServer struct{}

func (UnimplementedCapacityServer) Forecast(context.Context, *ForecastRequest) (*ForecastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forecast not implemented")
}
func (UnimplementedCapacityServer) Risks(context.Context, *RisksRequest) (*RisksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Risks not implemented")
}
func (UnimplementedCapacityServer) mustEmbedUnimplementedCapacityServer() {}
func (UnimplementedCapacityServer) testEmbeddedByValue()                  {}

// UnsafeCapacityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityServer will
// result in compilation errors.
type UnsafeCapacityServer interface {
	mustEmbedUnimplementedCapacityServer()
}

func RegisterCapacityServer(s grpc.ServiceRegistrar, srv CapacityServer) {
	// If the following call pancis, it indicates UnimplementedCapacityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Capacity_ServiceDesc, srv)
}

func _Capacity_Forecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServer).Forecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capacity_Forecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServer).Forecast(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Capacity_Risks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RisksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServer).Risks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capacity_Risks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServer).Risks(ctx, req.(*RisksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Capacity_ServiceDesc is the grpc.ServiceDesc for Capacity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Capacity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gough.v1.Capacity",
	HandlerType: (*CapacityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forecast",
			Handler:    _Capacity_Forecast_Handler,
		},
		{
			MethodName: "Risks",
			Handler:    _Capacity_Risks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gough/capacity.proto",
}
