// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gough/identity.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Identity_IssueSVID_FullMethodName  = "/gough.v1.Identity/IssueSVID"
	Identity_VerifyOTPN_FullMethodName = "/gough.v1.Identity/VerifyOTPN"
)

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityClient interface {
	IssueSVID(ctx context.Context, in *IssueSVIDRequest, opts ...grpc.CallOption) (*IssueSVIDResponse, error)
	VerifyOTPN(ctx context.Context, in *VerifyOTPNRequest, opts ...grpc.CallOption) (*VerifyOTPNResponse, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) IssueSVID(ctx context.Context, in *IssueSVIDRequest, opts ...grpc.CallOption) (*IssueSVIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueSVIDResponse)
	err := c.cc.Invoke(ctx, Identity_IssueSVID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) VerifyOTPN(ctx context.Context, in *VerifyOTPNRequest, opts ...grpc.CallOption) (*VerifyOTPNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOTPNResponse)
	err := c.cc.Invoke(ctx, Identity_VerifyOTPN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
// All implementations must embed UnimplementedIdentityServer
// for forward compatibility.
type IdentityServer interface {
	IssueSVID(context.Context, *IssueSVIDRequest) (*IssueSVIDResponse, error)
	VerifyOTPN(context.Context, *VerifyOTPNRequest) (*VerifyOTPNResponse, error)
	mustEmbedUnimplementedIdentityServer()
}

// UnimplementedIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServer struct{}

func (UnimplementedIdentityServer) IssueSVID(context.Context, *IssueSVIDRequest) (*IssueSVIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueSVID not implemented")
}
func (UnimplementedIdentityServer) VerifyOTPN(context.Context, *VerifyOTPNRequest) (*VerifyOTPNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyOTPN not implemented")
}
func (UnimplementedIdentityServer) mustEmbedUnimplementedIdentityServer() {}
func (UnimplementedIdentityServer) testEmbeddedByValue()                  {}

// UnsafeIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServer will
// result in compilation errors.
type UnsafeIdentityServer interface {
	mustEmbedUnimplementedIdentityServer()
}

func RegisterIdentityServer(s grpc.ServiceRegistrar, srv IdentityServer) {
	// If the following call pancis, it indicates UnimplementedIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identity_ServiceDesc, srv)
}

func _Identity_IssueSVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueSVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).IssueSVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_IssueSVID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).IssueSVID(ctx, req.(*IssueSVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_VerifyOTPN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).VerifyOTPN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_VerifyOTPN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).VerifyOTPN(ctx, req.(*VerifyOTPNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Identity_ServiceDesc is the grpc.ServiceDesc for Identity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gough.v1.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueSVID",
			Handler:    _Identity_IssueSVID_Handler,
		},
		{
			MethodName: "VerifyOTPN",
			Handler:    _Identity_VerifyOTPN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gough/identity.proto",
}
