// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gough/ipxe.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IPXE_ResolveBootScript_FullMethodName  = "/gough.v1.IPXE/ResolveBootScript"
	IPXE_BindMac_FullMethodName            = "/gough.v1.IPXE/BindMac"
	IPXE_MintBootstrapToken_FullMethodName = "/gough.v1.IPXE/MintBootstrapToken"
	IPXE_FetchCloudInit_FullMethodName     = "/gough.v1.IPXE/FetchCloudInit"
)

// IPXEClient is the client API for IPXE service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IPXEClient interface {
	ResolveBootScript(ctx context.Context, in *ResolveBootScriptRequest, opts ...grpc.CallOption) (*ResolveBootScriptResponse, error)
	BindMac(ctx context.Context, in *BindMacRequest, opts ...grpc.CallOption) (*BindMacResponse, error)
	MintBootstrapToken(ctx context.Context, in *MintBootstrapTokenRequest, opts ...grpc.CallOption) (*MintBootstrapTokenResponse, error)
	FetchCloudInit(ctx context.Context, in *FetchCloudInitRequest, opts ...grpc.CallOption) (*FetchCloudInitResponse, error)
}

type iPXEClient struct {
	cc grpc.ClientConnInterface
}

func NewIPXEClient(cc grpc.ClientConnInterface) IPXEClient {
	return &iPXEClient{cc}
}

func (c *iPXEClient) ResolveBootScript(ctx context.Context, in *ResolveBootScriptRequest, opts ...grpc.CallOption) (*ResolveBootScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveBootScriptResponse)
	err := c.cc.Invoke(ctx, IPXE_ResolveBootScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPXEClient) BindMac(ctx context.Context, in *BindMacRequest, opts ...grpc.CallOption) (*BindMacResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindMacResponse)
	err := c.cc.Invoke(ctx, IPXE_BindMac_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPXEClient) MintBootstrapToken(ctx context.Context, in *MintBootstrapTokenRequest, opts ...grpc.CallOption) (*MintBootstrapTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintBootstrapTokenResponse)
	err := c.cc.Invoke(ctx, IPXE_MintBootstrapToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPXEClient) FetchCloudInit(ctx context.Context, in *FetchCloudInitRequest, opts ...grpc.CallOption) (*FetchCloudInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchCloudInitResponse)
	err := c.cc.Invoke(ctx, IPXE_FetchCloudInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPXEServer is the server API for IPXE service.
// All implementations must embed UnimplementedIPXEServer
// for forward compatibility.
type IPXEServer interface {
	ResolveBootScript(context.Context, *ResolveBootScriptRequest) (*ResolveBootScriptResponse, error)
	BindMac(context.Context, *BindMacRequest) (*BindMacResponse, error)
	MintBootstrapToken(context.Context, *MintBootstrapTokenRequest) (*MintBootstrapTokenResponse, error)
	FetchCloudInit(context.Context, *FetchCloudInitRequest) (*FetchCloudInitResponse, error)
	mustEmbedUnimplementedIPXEServer()
}

// UnimplementedIPXEServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIPXEServer struct{}

func (UnimplementedIPXEServer) ResolveBootScript(context.Context, *ResolveBootScriptRequest) (*ResolveBootScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveBootScript not implemented")
}
func (UnimplementedIPXEServer) BindMac(context.Context, *BindMacRequest) (*BindMacResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindMac not implemented")
}
func (UnimplementedIPXEServer) MintBootstrapToken(context.Context, *MintBootstrapTokenRequest) (*MintBootstrapTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintBootstrapToken not implemented")
}
func (UnimplementedIPXEServer) FetchCloudInit(context.Context, *FetchCloudInitRequest) (*FetchCloudInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCloudInit not implemented")
}
func (UnimplementedIPXEServer) mustEmbedUnimplementedIPXEServer() {}
func (UnimplementedIPXEServer) testEmbeddedByValue()              {}

// UnsafeIPXEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPXEServer will
// result in compilation errors.
type UnsafeIPXEServer interface {
	mustEmbedUnimplementedIPXEServer()
}

func RegisterIPXEServer(s grpc.ServiceRegistrar, srv IPXEServer) {
	// If the following call pancis, it indicates UnimplementedIPXEServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IPXE_ServiceDesc, srv)
}

func _IPXE_ResolveBootScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveBootScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPXEServer).ResolveBootScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPXE_ResolveBootScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPXEServer).ResolveBootScript(ctx, req.(*ResolveBootScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPXE_BindMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindMacRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPXEServer).BindMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPXE_BindMac_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPXEServer).BindMac(ctx, req.(*BindMacRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPXE_MintBootstrapToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintBootstrapTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPXEServer).MintBootstrapToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPXE_MintBootstrapToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPXEServer).MintBootstrapToken(ctx, req.(*MintBootstrapTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPXE_FetchCloudInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCloudInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPXEServer).FetchCloudInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPXE_FetchCloudInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPXEServer).FetchCloudInit(ctx, req.(*FetchCloudInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IPXE_ServiceDesc is the grpc.ServiceDesc for IPXE service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPXE_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gough.v1.IPXE",
	HandlerType: (*IPXEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveBootScript",
			Handler:    _IPXE_ResolveBootScript_Handler,
		},
		{
			MethodName: "BindMac",
			Handler:    _IPXE_BindMac_Handler,
		},
		{
			MethodName: "MintBootstrapToken",
			Handler:    _IPXE_MintBootstrapToken_Handler,
		},
		{
			MethodName: "FetchCloudInit",
			Handler:    _IPXE_FetchCloudInit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gough/ipxe.proto",
}
