// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gough/joiner.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JoinerSecrets_Emit_FullMethodName    = "/gough.v1.JoinerSecrets/Emit"
	JoinerSecrets_Consume_FullMethodName = "/gough.v1.JoinerSecrets/Consume"
	JoinerSecrets_Rotate_FullMethodName  = "/gough.v1.JoinerSecrets/Rotate"
	JoinerSecrets_Revoke_FullMethodName  = "/gough.v1.JoinerSecrets/Revoke"
	JoinerSecrets_List_FullMethodName    = "/gough.v1.JoinerSecrets/List"
)

// JoinerSecretsClient is the client API for JoinerSecrets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoinerSecretsClient interface {
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error)
	Rotate(ctx context.Context, in *RotateRequest, opts ...grpc.CallOption) (*RotateResponse, error)
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
	List(ctx context.Context, in *JoinerListRequest, opts ...grpc.CallOption) (*JoinerListResponse, error)
}

type joinerSecretsClient struct {
	cc grpc.ClientConnInterface
}

func NewJoinerSecretsClient(cc grpc.ClientConnInterface) JoinerSecretsClient {
	return &joinerSecretsClient{cc}
}

func (c *joinerSecretsClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, JoinerSecrets_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joinerSecretsClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeResponse)
	err := c.cc.Invoke(ctx, JoinerSecrets_Consume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joinerSecretsClient) Rotate(ctx context.Context, in *RotateRequest, opts ...grpc.CallOption) (*RotateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateResponse)
	err := c.cc.Invoke(ctx, JoinerSecrets_Rotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joinerSecretsClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, JoinerSecrets_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joinerSecretsClient) List(ctx context.Context, in *JoinerListRequest, opts ...grpc.CallOption) (*JoinerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinerListResponse)
	err := c.cc.Invoke(ctx, JoinerSecrets_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoinerSecretsServer is the server API for JoinerSecrets service.
// All implementations must embed UnimplementedJoinerSecretsServer
// for forward compatibility.
type JoinerSecretsServer interface {
	Emit(context.Context, *EmitRequest) (*EmitResponse, error)
	Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error)
	Rotate(context.Context, *RotateRequest) (*RotateResponse, error)
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	List(context.Context, *JoinerListRequest) (*JoinerListResponse, error)
	mustEmbedUnimplementedJoinerSecretsServer()
}

// UnimplementedJoinerSecretsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJoinerSecretsServer struct{}

func (UnimplementedJoinerSecretsServer) Emit(context.Context, *EmitRequest) (*EmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedJoinerSecretsServer) Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedJoinerSecretsServer) Rotate(context.Context, *RotateRequest) (*RotateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rotate not implemented")
}
func (UnimplementedJoinerSecretsServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedJoinerSecretsServer) List(context.Context, *JoinerListRequest) (*JoinerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedJoinerSecretsServer) mustEmbedUnimplementedJoinerSecretsServer() {}
func (UnimplementedJoinerSecretsServer) testEmbeddedByValue()                       {}

// UnsafeJoinerSecretsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoinerSecretsServer will
// result in compilation errors.
type UnsafeJoinerSecretsServer interface {
	mustEmbedUnimplementedJoinerSecretsServer()
}

func RegisterJoinerSecretsServer(s grpc.ServiceRegistrar, srv JoinerSecretsServer) {
	// If the following call pancis, it indicates UnimplementedJoinerSecretsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JoinerSecrets_ServiceDesc, srv)
}

func _JoinerSecrets_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinerSecretsServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinerSecrets_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinerSecretsServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoinerSecrets_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinerSecretsServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinerSecrets_Consume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinerSecretsServer).Consume(ctx, req.(*ConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoinerSecrets_Rotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinerSecretsServer).Rotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinerSecrets_Rotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinerSecretsServer).Rotate(ctx, req.(*RotateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoinerSecrets_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinerSecretsServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinerSecrets_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinerSecretsServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoinerSecrets_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinerSecretsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinerSecrets_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinerSecretsServer).List(ctx, req.(*JoinerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JoinerSecrets_ServiceDesc is the grpc.ServiceDesc for JoinerSecrets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoinerSecrets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gough.v1.JoinerSecrets",
	HandlerType: (*JoinerSecretsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _JoinerSecrets_Emit_Handler,
		},
		{
			MethodName: "Consume",
			Handler:    _JoinerSecrets_Consume_Handler,
		},
		{
			MethodName: "Rotate",
			Handler:    _JoinerSecrets_Rotate_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _JoinerSecrets_Revoke_Handler,
		},
		{
			MethodName: "List",
			Handler:    _JoinerSecrets_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gough/joiner.proto",
}
