// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gough/migration.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migration_PolicyGet_FullMethodName      = "/gough.v1.Migration/PolicyGet"
	Migration_PolicyPatch_FullMethodName    = "/gough.v1.Migration/PolicyPatch"
	Migration_Trigger_FullMethodName        = "/gough.v1.Migration/Trigger"
	Migration_EventStream_FullMethodName    = "/gough.v1.Migration/EventStream"
	Migration_SafetyEnvelope_FullMethodName = "/gough.v1.Migration/SafetyEnvelope"
)

// MigrationClient is the client API for Migration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrationClient interface {
	PolicyGet(ctx context.Context, in *PolicyGetRequest, opts ...grpc.CallOption) (*PolicyGetResponse, error)
	PolicyPatch(ctx context.Context, in *PolicyPatchRequest, opts ...grpc.CallOption) (*PolicyPatchResponse, error)
	Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	EventStream(ctx context.Context, in *MigrationEventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationEventStreamResponse], error)
	SafetyEnvelope(ctx context.Context, in *SafetyEnvelopeRequest, opts ...grpc.CallOption) (*SafetyEnvelopeResponse, error)
}

type migrationClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrationClient(cc grpc.ClientConnInterface) MigrationClient {
	return &migrationClient{cc}
}

func (c *migrationClient) PolicyGet(ctx context.Context, in *PolicyGetRequest, opts ...grpc.CallOption) (*PolicyGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyGetResponse)
	err := c.cc.Invoke(ctx, Migration_PolicyGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) PolicyPatch(ctx context.Context, in *PolicyPatchRequest, opts ...grpc.CallOption) (*PolicyPatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyPatchResponse)
	err := c.cc.Invoke(ctx, Migration_PolicyPatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, Migration_Trigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) EventStream(ctx context.Context, in *MigrationEventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationEventStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Migration_ServiceDesc.Streams[0], Migration_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MigrationEventStreamRequest, MigrationEventStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_EventStreamClient = grpc.ServerStreamingClient[MigrationEventStreamResponse]

func (c *migrationClient) SafetyEnvelope(ctx context.Context, in *SafetyEnvelopeRequest, opts ...grpc.CallOption) (*SafetyEnvelopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafetyEnvelopeResponse)
	err := c.cc.Invoke(ctx, Migration_SafetyEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigrationServer is the server API for Migration service.
// All implementations must embed UnimplementedMigrationServer
// for forward compatibility.
type MigrationServer interface {
	PolicyGet(context.Context, *PolicyGetRequest) (*PolicyGetResponse, error)
	PolicyPatch(context.Context, *PolicyPatchRequest) (*PolicyPatchResponse, error)
	Trigger(context.Context, *TriggerRequest) (*TriggerResponse, error)
	EventStream(*MigrationEventStreamRequest, grpc.ServerStreamingServer[MigrationEventStreamResponse]) error
	SafetyEnvelope(context.Context, *SafetyEnvelopeRequest) (*SafetyEnvelopeResponse, error)
	mustEmbedUnimplementedMigrationServer()
}

// UnimplementedMigrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigrationServer struct{}

func (UnimplementedMigrationServer) PolicyGet(context.Context, *PolicyGetRequest) (*PolicyGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PolicyGet not implemented")
}
func (UnimplementedMigrationServer) PolicyPatch(context.Context, *PolicyPatchRequest) (*PolicyPatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PolicyPatch not implemented")
}
func (UnimplementedMigrationServer) Trigger(context.Context, *TriggerRequest) (*TriggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trigger not implemented")
}
func (UnimplementedMigrationServer) EventStream(*MigrationEventStreamRequest, grpc.ServerStreamingServer[MigrationEventStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedMigrationServer) SafetyEnvelope(context.Context, *SafetyEnvelopeRequest) (*SafetyEnvelopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SafetyEnvelope not implemented")
}
func (UnimplementedMigrationServer) mustEmbedUnimplementedMigrationServer() {}
func (UnimplementedMigrationServer) testEmbeddedByValue()                   {}

// UnsafeMigrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrationServer will
// result in compilation errors.
type UnsafeMigrationServer interface {
	mustEmbedUnimplementedMigrationServer()
}

func RegisterMigrationServer(s grpc.ServiceRegistrar, srv MigrationServer) {
	// If the following call pancis, it indicates UnimplementedMigrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migration_ServiceDesc, srv)
}

func _Migration_PolicyGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).PolicyGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_PolicyGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).PolicyGet(ctx, req.(*PolicyGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_PolicyPatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).PolicyPatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_PolicyPatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).PolicyPatch(ctx, req.(*PolicyPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_Trigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).Trigger(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MigrationEventStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MigrationServer).EventStream(m, &grpc.GenericServerStream[MigrationEventStreamRequest, MigrationEventStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_EventStreamServer = grpc.ServerStreamingServer[MigrationEventStreamResponse]

func _Migration_SafetyEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafetyEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).SafetyEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_SafetyEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).SafetyEnvelope(ctx, req.(*SafetyEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Migration_ServiceDesc is the grpc.ServiceDesc for Migration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gough.v1.Migration",
	HandlerType: (*MigrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PolicyGet",
			Handler:    _Migration_PolicyGet_Handler,
		},
		{
			MethodName: "PolicyPatch",
			Handler:    _Migration_PolicyPatch_Handler,
		},
		{
			MethodName: "Trigger",
			Handler:    _Migration_Trigger_Handler,
		},
		{
			MethodName: "SafetyEnvelope",
			Handler:    _Migration_SafetyEnvelope_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _Migration_EventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gough/migration.proto",
}
