// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: gough/migration.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
}

func (x *PolicyGetRequest) Reset() {
	*x = PolicyGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGetRequest) ProtoMessage() {}

func (x *PolicyGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGetRequest.ProtoReflect.Descriptor instead.
func (*PolicyGetRequest) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyGetRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type PolicyGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId   string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyData string `protobuf:"bytes,2,opt,name=policy_data,json=policyData,proto3" json:"policy_data,omitempty"`
}

func (x *PolicyGetResponse) Reset() {
	*x = PolicyGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGetResponse) ProtoMessage() {}

func (x *PolicyGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGetResponse.ProtoReflect.Descriptor instead.
func (*PolicyGetResponse) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyGetResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyGetResponse) GetPolicyData() string {
	if x != nil {
		return x.PolicyData
	}
	return ""
}

type PolicyPatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId  string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PatchData string `protobuf:"bytes,2,opt,name=patch_data,json=patchData,proto3" json:"patch_data,omitempty"`
}

func (x *PolicyPatchRequest) Reset() {
	*x = PolicyPatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyPatchRequest) ProtoMessage() {}

func (x *PolicyPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyPatchRequest.ProtoReflect.Descriptor instead.
func (*PolicyPatchRequest) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyPatchRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyPatchRequest) GetPatchData() string {
	if x != nil {
		return x.PatchData
	}
	return ""
}

type PolicyPatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId   string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyData string `protobuf:"bytes,2,opt,name=policy_data,json=policyData,proto3" json:"policy_data,omitempty"`
}

func (x *PolicyPatchResponse) Reset() {
	*x = PolicyPatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyPatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyPatchResponse) ProtoMessage() {}

func (x *PolicyPatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyPatchResponse.ProtoReflect.Descriptor instead.
func (*PolicyPatchResponse) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyPatchResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyPatchResponse) GetPolicyData() string {
	if x != nil {
		return x.PolicyData
	}
	return ""
}

type TriggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId   int64  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	TargetNodeId int64  `protobuf:"varint,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Strategy     string `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	DrainFirst   bool   `protobuf:"varint,4,opt,name=drain_first,json=drainFirst,proto3" json:"drain_first,omitempty"`
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *TriggerRequest) GetTargetNodeId() int64 {
	if x != nil {
		return x.TargetNodeId
	}
	return 0
}

func (x *TriggerRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *TriggerRequest) GetDrainFirst() bool {
	if x != nil {
		return x.DrainFirst
	}
	return false
}

type TriggerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MigrationId string `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

type MigrationEventStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	EventTypes []string `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
}

func (x *MigrationEventStreamRequest) Reset() {
	*x = MigrationEventStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationEventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationEventStreamRequest) ProtoMessage() {}

func (x *MigrationEventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationEventStreamRequest.ProtoReflect.Descriptor instead.
func (*MigrationEventStreamRequest) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{6}
}

func (x *MigrationEventStreamRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *MigrationEventStreamRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type MigrationEventStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload   string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MigrationEventStreamResponse) Reset() {
	*x = MigrationEventStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationEventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationEventStreamResponse) ProtoMessage() {}

func (x *MigrationEventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationEventStreamResponse.ProtoReflect.Descriptor instead.
func (*MigrationEventStreamResponse) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{7}
}

func (x *MigrationEventStreamResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MigrationEventStreamResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MigrationEventStreamResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SafetyEnvelopeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvelopeData string `protobuf:"bytes,1,opt,name=envelope_data,json=envelopeData,proto3" json:"envelope_data,omitempty"`
}

func (x *SafetyEnvelopeRequest) Reset() {
	*x = SafetyEnvelopeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SafetyEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyEnvelopeRequest) ProtoMessage() {}

func (x *SafetyEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*SafetyEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{8}
}

func (x *SafetyEnvelopeRequest) GetEnvelopeData() string {
	if x != nil {
		return x.EnvelopeData
	}
	return ""
}

type SafetyEnvelopeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid            bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ValidationResult string `protobuf:"bytes,2,opt,name=validation_result,json=validationResult,proto3" json:"validation_result,omitempty"`
}

func (x *SafetyEnvelopeResponse) Reset() {
	*x = SafetyEnvelopeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gough_migration_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SafetyEnvelopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyEnvelopeResponse) ProtoMessage() {}

func (x *SafetyEnvelopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gough_migration_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyEnvelopeResponse.ProtoReflect.Descriptor instead.
func (*SafetyEnvelopeResponse) Descriptor() ([]byte, []int) {
	return file_gough_migration_proto_rawDescGZIP(), []int{9}
}

func (x *SafetyEnvelopeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *SafetyEnvelopeResponse) GetValidationResult() string {
	if x != nil {
		return x.ValidationResult
	}
	return ""
}

var File_gough_migration_proto protoreflect.FileDescriptor

var file_gough_migration_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76,
	0x31, 0x22, 0x2f, 0x0a, 0x10, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x49, 0x64, 0x22, 0x51, 0x0a, 0x11, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x12, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x13, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x94, 0x01, 0x0a,
	0x0e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x0f, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x1b, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x75, 0x0a, 0x1c, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3c, 0x0a, 0x15, 0x53, 0x61, 0x66, 0x65,
	0x74, 0x79, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a, 0x16, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79,
	0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x92, 0x03, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x44, 0x0a, 0x09, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x47, 0x65, 0x74, 0x12, 0x1a,
	0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x75,
	0x67, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x50, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x18,
	0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x25, 0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x6f, 0x75, 0x67,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x12, 0x53, 0x0a, 0x0e, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79, 0x45, 0x6e, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x61, 0x66, 0x65, 0x74, 0x79, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x74, 0x65,
	0x63, 0x68, 0x69, 0x6e, 0x63, 0x2f, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2d, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x75, 0x67, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gough_migration_proto_rawDescOnce sync.Once
	file_gough_migration_proto_rawDescData = file_gough_migration_proto_rawDesc
)

func file_gough_migration_proto_rawDescGZIP() []byte {
	file_gough_migration_proto_rawDescOnce.Do(func() {
		file_gough_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_gough_migration_proto_rawDescData)
	})
	return file_gough_migration_proto_rawDescData
}

var file_gough_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gough_migration_proto_goTypes = []any{
	(*PolicyGetRequest)(nil),             // 0: gough.v1.PolicyGetRequest
	(*PolicyGetResponse)(nil),            // 1: gough.v1.PolicyGetResponse
	(*PolicyPatchRequest)(nil),           // 2: gough.v1.PolicyPatchRequest
	(*PolicyPatchResponse)(nil),          // 3: gough.v1.PolicyPatchResponse
	(*TriggerRequest)(nil),               // 4: gough.v1.TriggerRequest
	(*TriggerResponse)(nil),              // 5: gough.v1.TriggerResponse
	(*MigrationEventStreamRequest)(nil),  // 6: gough.v1.MigrationEventStreamRequest
	(*MigrationEventStreamResponse)(nil), // 7: gough.v1.MigrationEventStreamResponse
	(*SafetyEnvelopeRequest)(nil),        // 8: gough.v1.SafetyEnvelopeRequest
	(*SafetyEnvelopeResponse)(nil),       // 9: gough.v1.SafetyEnvelopeResponse
}
var file_gough_migration_proto_depIdxs = []int32{
	0, // 0: gough.v1.Migration.PolicyGet:input_type -> gough.v1.PolicyGetRequest
	2, // 1: gough.v1.Migration.PolicyPatch:input_type -> gough.v1.PolicyPatchRequest
	4, // 2: gough.v1.Migration.Trigger:input_type -> gough.v1.TriggerRequest
	6, // 3: gough.v1.Migration.EventStream:input_type -> gough.v1.MigrationEventStreamRequest
	8, // 4: gough.v1.Migration.SafetyEnvelope:input_type -> gough.v1.SafetyEnvelopeRequest
	1, // 5: gough.v1.Migration.PolicyGet:output_type -> gough.v1.PolicyGetResponse
	3, // 6: gough.v1.Migration.PolicyPatch:output_type -> gough.v1.PolicyPatchResponse
	5, // 7: gough.v1.Migration.Trigger:output_type -> gough.v1.TriggerResponse
	7, // 8: gough.v1.Migration.EventStream:output_type -> gough.v1.MigrationEventStreamResponse
	9, // 9: gough.v1.Migration.SafetyEnvelope:output_type -> gough.v1.SafetyEnvelopeResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gough_migration_proto_init() }
func file_gough_migration_proto_init() {
	if File_gough_migration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gough_migration_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PolicyGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PolicyGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PolicyPatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PolicyPatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TriggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TriggerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MigrationEventStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MigrationEventStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SafetyEnvelopeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gough_migration_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SafetyEnvelopeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gough_migration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gough_migration_proto_goTypes,
		DependencyIndexes: file_gough_migration_proto_depIdxs,
		MessageInfos:      file_gough_migration_proto_msgTypes,
	}.Build()
	File_gough_migration_proto = out.File
	file_gough_migration_proto_rawDesc = nil
	file_gough_migration_proto_goTypes = nil
	file_gough_migration_proto_depIdxs = nil
}
