// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gough/primary.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Primary_Status_FullMethodName         = "/gough.v1.Primary/Status"
	Primary_Replace_FullMethodName        = "/gough.v1.Primary/Replace"
	Primary_ForceRecover_FullMethodName   = "/gough.v1.Primary/ForceRecover"
	Primary_FrontendSwitch_FullMethodName = "/gough.v1.Primary/FrontendSwitch"
	Primary_RotateCA_FullMethodName       = "/gough.v1.Primary/RotateCA"
)

// PrimaryClient is the client API for Primary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimaryClient interface {
	Status(ctx context.Context, in *PrimaryStatusRequest, opts ...grpc.CallOption) (*PrimaryStatusResponse, error)
	Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error)
	ForceRecover(ctx context.Context, in *ForceRecoverRequest, opts ...grpc.CallOption) (*ForceRecoverResponse, error)
	FrontendSwitch(ctx context.Context, in *FrontendSwitchRequest, opts ...grpc.CallOption) (*FrontendSwitchResponse, error)
	RotateCA(ctx context.Context, in *RotateCARequest, opts ...grpc.CallOption) (*RotateCAResponse, error)
}

type primaryClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimaryClient(cc grpc.ClientConnInterface) PrimaryClient {
	return &primaryClient{cc}
}

func (c *primaryClient) Status(ctx context.Context, in *PrimaryStatusRequest, opts ...grpc.CallOption) (*PrimaryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrimaryStatusResponse)
	err := c.cc.Invoke(ctx, Primary_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryClient) Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceResponse)
	err := c.cc.Invoke(ctx, Primary_Replace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryClient) ForceRecover(ctx context.Context, in *ForceRecoverRequest, opts ...grpc.CallOption) (*ForceRecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceRecoverResponse)
	err := c.cc.Invoke(ctx, Primary_ForceRecover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryClient) FrontendSwitch(ctx context.Context, in *FrontendSwitchRequest, opts ...grpc.CallOption) (*FrontendSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrontendSwitchResponse)
	err := c.cc.Invoke(ctx, Primary_FrontendSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryClient) RotateCA(ctx context.Context, in *RotateCARequest, opts ...grpc.CallOption) (*RotateCAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCAResponse)
	err := c.cc.Invoke(ctx, Primary_RotateCA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimaryServer is the server API for Primary service.
// All implementations must embed UnimplementedPrimaryServer
// for forward compatibility.
type PrimaryServer interface {
	Status(context.Context, *PrimaryStatusRequest) (*PrimaryStatusResponse, error)
	Replace(context.Context, *ReplaceRequest) (*ReplaceResponse, error)
	ForceRecover(context.Context, *ForceRecoverRequest) (*ForceRecoverResponse, error)
	FrontendSwitch(context.Context, *FrontendSwitchRequest) (*FrontendSwitchResponse, error)
	RotateCA(context.Context, *RotateCARequest) (*RotateCAResponse, error)
	mustEmbedUnimplementedPrimaryServer()
}

// UnimplementedPrimaryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimaryServer struct{}

func (UnimplementedPrimaryServer) Status(context.Context, *PrimaryStatusRequest) (*PrimaryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPrimaryServer) Replace(context.Context, *ReplaceRequest) (*ReplaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replace not implemented")
}
func (UnimplementedPrimaryServer) ForceRecover(context.Context, *ForceRecoverRequest) (*ForceRecoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceRecover not implemented")
}
func (UnimplementedPrimaryServer) FrontendSwitch(context.Context, *FrontendSwitchRequest) (*FrontendSwitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FrontendSwitch not implemented")
}
func (UnimplementedPrimaryServer) RotateCA(context.Context, *RotateCARequest) (*RotateCAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateCA not implemented")
}
func (UnimplementedPrimaryServer) mustEmbedUnimplementedPrimaryServer() {}
func (UnimplementedPrimaryServer) testEmbeddedByValue()                 {}

// UnsafePrimaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimaryServer will
// result in compilation errors.
type UnsafePrimaryServer interface {
	mustEmbedUnimplementedPrimaryServer()
}

func RegisterPrimaryServer(s grpc.ServiceRegistrar, srv PrimaryServer) {
	// If the following call pancis, it indicates UnimplementedPrimaryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Primary_ServiceDesc, srv)
}

func _Primary_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Primary_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServer).Status(ctx, req.(*PrimaryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Primary_Replace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServer).Replace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Primary_Replace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServer).Replace(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Primary_ForceRecover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceRecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServer).ForceRecover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Primary_ForceRecover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServer).ForceRecover(ctx, req.(*ForceRecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Primary_FrontendSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrontendSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServer).FrontendSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Primary_FrontendSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServer).FrontendSwitch(ctx, req.(*FrontendSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Primary_RotateCA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServer).RotateCA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Primary_RotateCA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServer).RotateCA(ctx, req.(*RotateCARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Primary_ServiceDesc is the grpc.ServiceDesc for Primary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Primary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gough.v1.Primary",
	HandlerType: (*PrimaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Primary_Status_Handler,
		},
		{
			MethodName: "Replace",
			Handler:    _Primary_Replace_Handler,
		},
		{
			MethodName: "ForceRecover",
			Handler:    _Primary_ForceRecover_Handler,
		},
		{
			MethodName: "FrontendSwitch",
			Handler:    _Primary_FrontendSwitch_Handler,
		},
		{
			MethodName: "RotateCA",
			Handler:    _Primary_RotateCA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gough/primary.proto",
}
