# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gough/audit.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'gough/audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gough/audit.proto\x12\x08gough.v1\"3\n\x12\x41ppendEventRequest\x12\x1d\n\nevent_data\x18\x01 \x01(\tR\teventData\"N\n\x13\x41ppendEventResponse\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12\x1c\n\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"J\n\rStreamRequest\x12\x16\n\x06\x66ilter\x18\x01 \x01(\tR\x06\x66ilter\x12!\n\x0cstart_offset\x18\x02 \x01(\x03R\x0bstartOffset\"n\n\x0eStreamResponse\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12#\n\revent_payload\x18\x02 \x01(\tR\x0c\x65ventPayload\x12\x1c\n\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"*\n\rVerifyRequest\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\"]\n\x0eVerifyResponse\x12\x1a\n\x08verified\x18\x01 \x01(\x08R\x08verified\x12/\n\x13verification_result\x18\x02 \x01(\tR\x12verificationResult\"f\n\x12\x45xportRangeRequest\x12\x1d\n\nstart_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n\x08\x65nd_time\x18\x02 \x01(\x03R\x07\x65ndTime\x12\x16\n\x06\x66ormat\x18\x03 \x01(\tR\x06\x66ormat\"S\n\x13\x45xportRangeResponse\x12\x1f\n\x0b\x65xport_data\x18\x01 \x01(\x0cR\nexportData\x12\x1b\n\texport_id\x18\x02 \x01(\tR\x08\x65xportId2\x9b\x02\n\x05\x41udit\x12J\n\x0b\x41ppendEvent\x12\x1c.gough.v1.AppendEventRequest\x1a\x1d.gough.v1.AppendEventResponse\x12=\n\x06Stream\x12\x17.gough.v1.StreamRequest\x1a\x18.gough.v1.StreamResponse0\x01\x12;\n\x06Verify\x12\x17.gough.v1.VerifyRequest\x1a\x18.gough.v1.VerifyResponse\x12J\n\x0b\x45xportRange\x12\x1c.gough.v1.ExportRangeRequest\x1a\x1d.gough.v1.ExportRangeResponseBTZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gough.audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1'
  _globals['_APPENDEVENTREQUEST']._serialized_start=31
  _globals['_APPENDEVENTREQUEST']._serialized_end=82
  _globals['_APPENDEVENTRESPONSE']._serialized_start=84
  _globals['_APPENDEVENTRESPONSE']._serialized_end=162
  _globals['_STREAMREQUEST']._serialized_start=164
  _globals['_STREAMREQUEST']._serialized_end=238
  _globals['_STREAMRESPONSE']._serialized_start=240
  _globals['_STREAMRESPONSE']._serialized_end=350
  _globals['_VERIFYREQUEST']._serialized_start=352
  _globals['_VERIFYREQUEST']._serialized_end=394
  _globals['_VERIFYRESPONSE']._serialized_start=396
  _globals['_VERIFYRESPONSE']._serialized_end=489
  _globals['_EXPORTRANGEREQUEST']._serialized_start=491
  _globals['_EXPORTRANGEREQUEST']._serialized_end=593
  _globals['_EXPORTRANGERESPONSE']._serialized_start=595
  _globals['_EXPORTRANGERESPONSE']._serialized_end=678
  _globals['_AUDIT']._serialized_start=681
  _globals['_AUDIT']._serialized_end=964
# @@protoc_insertion_point(module_scope)
