# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gough import audit_pb2 as gough_dot_audit__pb2


class AuditStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEvent = channel.unary_unary(
                '/gough.v1.Audit/AppendEvent',
                request_serializer=gough_dot_audit__pb2.AppendEventRequest.SerializeToString,
                response_deserializer=gough_dot_audit__pb2.AppendEventResponse.FromString,
                _registered_method=True)
        self.Stream = channel.unary_stream(
                '/gough.v1.Audit/Stream',
                request_serializer=gough_dot_audit__pb2.StreamRequest.SerializeToString,
                response_deserializer=gough_dot_audit__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/gough.v1.Audit/Verify',
                request_serializer=gough_dot_audit__pb2.VerifyRequest.SerializeToString,
                response_deserializer=gough_dot_audit__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.ExportRange = channel.unary_unary(
                '/gough.v1.Audit/ExportRange',
                request_serializer=gough_dot_audit__pb2.ExportRangeRequest.SerializeToString,
                response_deserializer=gough_dot_audit__pb2.ExportRangeResponse.FromString,
                _registered_method=True)


class AuditServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AppendEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvent,
                    request_deserializer=gough_dot_audit__pb2.AppendEventRequest.FromString,
                    response_serializer=gough_dot_audit__pb2.AppendEventResponse.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=gough_dot_audit__pb2.StreamRequest.FromString,
                    response_serializer=gough_dot_audit__pb2.StreamResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=gough_dot_audit__pb2.VerifyRequest.FromString,
                    response_serializer=gough_dot_audit__pb2.VerifyResponse.SerializeToString,
            ),
            'ExportRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportRange,
                    request_deserializer=gough_dot_audit__pb2.ExportRangeRequest.FromString,
                    response_serializer=gough_dot_audit__pb2.ExportRangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gough.v1.Audit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gough.v1.Audit', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Audit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AppendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Audit/AppendEvent',
            gough_dot_audit__pb2.AppendEventRequest.SerializeToString,
            gough_dot_audit__pb2.AppendEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gough.v1.Audit/Stream',
            gough_dot_audit__pb2.StreamRequest.SerializeToString,
            gough_dot_audit__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Audit/Verify',
            gough_dot_audit__pb2.VerifyRequest.SerializeToString,
            gough_dot_audit__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Audit/ExportRange',
            gough_dot_audit__pb2.ExportRangeRequest.SerializeToString,
            gough_dot_audit__pb2.ExportRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
