# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gough/capacity.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'gough/capacity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gough/capacity.proto\x12\x08gough.v1\"J\n\x0f\x46orecastRequest\x12!\n\x0ctime_horizon\x18\x01 \x01(\tR\x0btimeHorizon\x12\x14\n\x05scope\x18\x02 \x01(\tR\x05scope\"X\n\x10\x46orecastResponse\x12\x1f\n\x0b\x66orecast_id\x18\x01 \x01(\tR\nforecastId\x12#\n\rforecast_data\x18\x02 \x01(\tR\x0c\x66orecastData\"$\n\x0cRisksRequest\x12\x14\n\x05scope\x18\x01 \x01(\tR\x05scope\"5\n\rRisksResponse\x12$\n\x05risks\x18\x01 \x03(\x0b\x32\x0e.gough.v1.RiskR\x05risks\"T\n\x04Risk\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n\x08severity\x18\x02 \x01(\tR\x08severity\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription2\x87\x01\n\x08\x43\x61pacity\x12\x41\n\x08\x46orecast\x12\x19.gough.v1.ForecastRequest\x1a\x1a.gough.v1.ForecastResponse\x12\x38\n\x05Risks\x12\x16.gough.v1.RisksRequest\x1a\x17.gough.v1.RisksResponseBTZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gough.capacity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1'
  _globals['_FORECASTREQUEST']._serialized_start=34
  _globals['_FORECASTREQUEST']._serialized_end=108
  _globals['_FORECASTRESPONSE']._serialized_start=110
  _globals['_FORECASTRESPONSE']._serialized_end=198
  _globals['_RISKSREQUEST']._serialized_start=200
  _globals['_RISKSREQUEST']._serialized_end=236
  _globals['_RISKSRESPONSE']._serialized_start=238
  _globals['_RISKSRESPONSE']._serialized_end=291
  _globals['_RISK']._serialized_start=293
  _globals['_RISK']._serialized_end=377
  _globals['_CAPACITY']._serialized_start=380
  _globals['_CAPACITY']._serialized_end=515
# @@protoc_insertion_point(module_scope)
