# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gough/discovery.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'gough/discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gough/discovery.proto\x12\x08gough.v1\"1\n\x0cProbeRequest\x12!\n\x0cprobe_params\x18\x01 \x01(\tR\x0bprobeParams\"M\n\rProbeResponse\x12!\n\x0cprobe_result\x18\x01 \x01(\tR\x0bprobeResult\x12\x19\n\x08probe_id\x18\x02 \x01(\tR\x07probeId\"a\n\x1b\x44iscoveryEventStreamRequest\x12!\n\x0c\x65vent_filter\x18\x01 \x01(\tR\x0b\x65ventFilter\x12\x1f\n\x0b\x65vent_types\x18\x02 \x03(\tR\neventTypes\"b\n\x1c\x44iscoveryEventStreamResponse\x12\x1d\n\nevent_type\x18\x01 \x01(\tR\teventType\x12#\n\revent_payload\x18\x02 \x01(\tR\x0c\x65ventPayload\"F\n\x12\x45xecCommandRequest\x12\x18\n\x07\x63ommand\x18\x01 \x01(\tR\x07\x63ommand\x12\x16\n\x06target\x18\x02 \x01(\tR\x06target\"J\n\x13\x45xecCommandResponse\x12\x16\n\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n\texit_code\x18\x02 \x01(\x05R\x08\x65xitCode\"I\n\x14\x45xtractSecretRequest\x12\x1b\n\tsecret_id\x18\x01 \x01(\tR\x08secretId\x12\x14\n\x05scope\x18\x02 \x01(\tR\x05scope\":\n\x15\x45xtractSecretResponse\x12!\n\x0csecret_value\x18\x01 \x01(\tR\x0bsecretValue2\xc5\x02\n\tDiscovery\x12\x38\n\x05Probe\x12\x16.gough.v1.ProbeRequest\x1a\x17.gough.v1.ProbeResponse\x12`\n\x0b\x45ventStream\x12%.gough.v1.DiscoveryEventStreamRequest\x1a&.gough.v1.DiscoveryEventStreamResponse(\x01\x30\x01\x12J\n\x0b\x45xecCommand\x12\x1c.gough.v1.ExecCommandRequest\x1a\x1d.gough.v1.ExecCommandResponse\x12P\n\rExtractSecret\x12\x1e.gough.v1.ExtractSecretRequest\x1a\x1f.gough.v1.ExtractSecretResponseBTZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gough.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1'
  _globals['_PROBEREQUEST']._serialized_start=35
  _globals['_PROBEREQUEST']._serialized_end=84
  _globals['_PROBERESPONSE']._serialized_start=86
  _globals['_PROBERESPONSE']._serialized_end=163
  _globals['_DISCOVERYEVENTSTREAMREQUEST']._serialized_start=165
  _globals['_DISCOVERYEVENTSTREAMREQUEST']._serialized_end=262
  _globals['_DISCOVERYEVENTSTREAMRESPONSE']._serialized_start=264
  _globals['_DISCOVERYEVENTSTREAMRESPONSE']._serialized_end=362
  _globals['_EXECCOMMANDREQUEST']._serialized_start=364
  _globals['_EXECCOMMANDREQUEST']._serialized_end=434
  _globals['_EXECCOMMANDRESPONSE']._serialized_start=436
  _globals['_EXECCOMMANDRESPONSE']._serialized_end=510
  _globals['_EXTRACTSECRETREQUEST']._serialized_start=512
  _globals['_EXTRACTSECRETREQUEST']._serialized_end=585
  _globals['_EXTRACTSECRETRESPONSE']._serialized_start=587
  _globals['_EXTRACTSECRETRESPONSE']._serialized_end=645
  _globals['_DISCOVERY']._serialized_start=648
  _globals['_DISCOVERY']._serialized_end=973
# @@protoc_insertion_point(module_scope)
