# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gough import disks_pb2 as gough_dot_disks__pb2


class DisksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/gough.v1.Disks/List',
                request_serializer=gough_dot_disks__pb2.DiskListRequest.SerializeToString,
                response_deserializer=gough_dot_disks__pb2.DiskListResponse.FromString,
                _registered_method=True)
        self.Plan = channel.unary_unary(
                '/gough.v1.Disks/Plan',
                request_serializer=gough_dot_disks__pb2.PlanRequest.SerializeToString,
                response_deserializer=gough_dot_disks__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.Patch = channel.unary_unary(
                '/gough.v1.Disks/Patch',
                request_serializer=gough_dot_disks__pb2.DiskPatchRequest.SerializeToString,
                response_deserializer=gough_dot_disks__pb2.DiskPatchResponse.FromString,
                _registered_method=True)
        self.SmartRecheck = channel.unary_unary(
                '/gough.v1.Disks/SmartRecheck',
                request_serializer=gough_dot_disks__pb2.SmartRecheckRequest.SerializeToString,
                response_deserializer=gough_dot_disks__pb2.SmartRecheckResponse.FromString,
                _registered_method=True)


class DisksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Plan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Patch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SmartRecheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=gough_dot_disks__pb2.DiskListRequest.FromString,
                    response_serializer=gough_dot_disks__pb2.DiskListResponse.SerializeToString,
            ),
            'Plan': grpc.unary_unary_rpc_method_handler(
                    servicer.Plan,
                    request_deserializer=gough_dot_disks__pb2.PlanRequest.FromString,
                    response_serializer=gough_dot_disks__pb2.PlanResponse.SerializeToString,
            ),
            'Patch': grpc.unary_unary_rpc_method_handler(
                    servicer.Patch,
                    request_deserializer=gough_dot_disks__pb2.DiskPatchRequest.FromString,
                    response_serializer=gough_dot_disks__pb2.DiskPatchResponse.SerializeToString,
            ),
            'SmartRecheck': grpc.unary_unary_rpc_method_handler(
                    servicer.SmartRecheck,
                    request_deserializer=gough_dot_disks__pb2.SmartRecheckRequest.FromString,
                    response_serializer=gough_dot_disks__pb2.SmartRecheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gough.v1.Disks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gough.v1.Disks', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Disks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Disks/List',
            gough_dot_disks__pb2.DiskListRequest.SerializeToString,
            gough_dot_disks__pb2.DiskListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Plan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Disks/Plan',
            gough_dot_disks__pb2.PlanRequest.SerializeToString,
            gough_dot_disks__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Patch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Disks/Patch',
            gough_dot_disks__pb2.DiskPatchRequest.SerializeToString,
            gough_dot_disks__pb2.DiskPatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SmartRecheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Disks/SmartRecheck',
            gough_dot_disks__pb2.SmartRecheckRequest.SerializeToString,
            gough_dot_disks__pb2.SmartRecheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
