# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gough/identity.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'gough/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gough/identity.proto\x12\x08gough.v1\"o\n\x10IssueSVIDRequest\x12!\n\x0cservice_name\x18\x01 \x01(\tR\x0bserviceName\x12\x1f\n\x0bttl_seconds\x18\x02 \x01(\x05R\nttlSeconds\x12\x17\n\x07\x63sr_pem\x18\x03 \x01(\tR\x06\x63srPem\"\xa0\x01\n\x11IssueSVIDResponse\x12\'\n\x0f\x63\x65rtificate_pem\x18\x01 \x01(\tR\x0e\x63\x65rtificatePem\x12&\n\x0fprivate_key_pem\x18\x02 \x01(\tR\rprivateKeyPem\x12\x1d\n\nexpires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x1b\n\tspiffe_id\x18\x04 \x01(\tR\x08spiffeId\"p\n\x11VerifyOTPNRequest\x12\x17\n\x07node_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n\totp_token\x18\x02 \x01(\tR\x08otpToken\x12%\n\x0erotation_class\x18\x03 \x01(\tR\rrotationClass\"\x95\x01\n\x12VerifyOTPNResponse\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid\x12)\n\x10\x64\x65\x63rypted_secret\x18\x02 \x01(\x0cR\x0f\x64\x65\x63ryptedSecret\x12%\n\x0erotation_class\x18\x03 \x01(\tR\rrotationClass\x12\x17\n\x07node_id\x18\x04 \x01(\tR\x06nodeId2\x99\x01\n\x08Identity\x12\x44\n\tIssueSVID\x12\x1a.gough.v1.IssueSVIDRequest\x1a\x1b.gough.v1.IssueSVIDResponse\x12G\n\nVerifyOTPN\x12\x1b.gough.v1.VerifyOTPNRequest\x1a\x1c.gough.v1.VerifyOTPNResponseBTZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gough.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1'
  _globals['_ISSUESVIDREQUEST']._serialized_start=34
  _globals['_ISSUESVIDREQUEST']._serialized_end=145
  _globals['_ISSUESVIDRESPONSE']._serialized_start=148
  _globals['_ISSUESVIDRESPONSE']._serialized_end=308
  _globals['_VERIFYOTPNREQUEST']._serialized_start=310
  _globals['_VERIFYOTPNREQUEST']._serialized_end=422
  _globals['_VERIFYOTPNRESPONSE']._serialized_start=425
  _globals['_VERIFYOTPNRESPONSE']._serialized_end=574
  _globals['_IDENTITY']._serialized_start=577
  _globals['_IDENTITY']._serialized_end=730
# @@protoc_insertion_point(module_scope)
