# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gough/identity.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'gough/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gough/identity.proto\x12\x08gough.v1\"R\n\x10IssueSVIDRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x12\n\nttl_seconds\x18\x02 \x01(\x05\x12\x14\n\x07\x63sr_pem\x18\x03 \x01(\tR\x06\x63srPem\"\x9c\x01\n\x11IssueSVIDResponse\x12 \n\x0e\x63\x65rtificate_pem\x18\x01 \x01(\tR\rcertificatePem\x12\x1a\n\rprivate_key_pem\x18\x02 \x01(\tR\x0cprivateKeyPem\x12\x12\n\nexpires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x1f\n\nspiffe_id\x18\x04 \x01(\tR\tspiffeId\"S\n\x0fVerifyOTPNRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\totp_token\x18\x02 \x01(\t\x12\x16\n\x0erotation_class\x18\x03 \x01(\t\"\x7f\n\x10VerifyOTPNResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x18\n\x10\x64\x65\x63rypted_secret\x18\x02 \x01(\x0c\x12\x16\n\x0erotation_class\x18\x03 \x01(\t\x12\x0f\n\x07node_id\x18\x04 \x01(\t2\x8e\x01\n\x08Identity\x12S\n\tIssueSVID\x12\x1a.gough.v1.IssueSVIDRequest\x1a\x1b.gough.v1.IssueSVIDResponse\x12\x33\n\x08VerifyOTPN\x12\x19.gough.v1.VerifyOTPNRequest\x1a\x1a.gough.v1.VerifyOTPNResponseBTZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gough.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1'
  _globals['_ISSUESVFDREQUEST']._serialized_start=34
  _globals['_ISSUESVFDREQUEST']._serialized_end=116
  _globals['_ISSUESVFDRESPONSE']._serialized_start=118
  _globals['_ISSUESVFDRESPONSE']._serialized_end=274
  _globals['_VERIFYOTPNREQUEST']._serialized_start=276
  _globals['_VERIFYOTPNREQUEST']._serialized_end=359
  _globals['_VERIFYOTPNRESPONSE']._serialized_start=361
  _globals['_VERIFYOTPNRESPONSE']._serialized_end=484
  _globals['_IDENTITY']._serialized_start=486
  _globals['_IDENTITY']._serialized_end=628
# @@protoc_insertion_point(module_scope)
