# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gough import ipxe_pb2 as gough_dot_ipxe__pb2


class IPXEStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveBootScript = channel.unary_unary(
                '/gough.v1.IPXE/ResolveBootScript',
                request_serializer=gough_dot_ipxe__pb2.ResolveBootScriptRequest.SerializeToString,
                response_deserializer=gough_dot_ipxe__pb2.ResolveBootScriptResponse.FromString,
                _registered_method=True)
        self.BindMac = channel.unary_unary(
                '/gough.v1.IPXE/BindMac',
                request_serializer=gough_dot_ipxe__pb2.BindMacRequest.SerializeToString,
                response_deserializer=gough_dot_ipxe__pb2.BindMacResponse.FromString,
                _registered_method=True)
        self.MintBootstrapToken = channel.unary_unary(
                '/gough.v1.IPXE/MintBootstrapToken',
                request_serializer=gough_dot_ipxe__pb2.MintBootstrapTokenRequest.SerializeToString,
                response_deserializer=gough_dot_ipxe__pb2.MintBootstrapTokenResponse.FromString,
                _registered_method=True)
        self.FetchCloudInit = channel.unary_unary(
                '/gough.v1.IPXE/FetchCloudInit',
                request_serializer=gough_dot_ipxe__pb2.FetchCloudInitRequest.SerializeToString,
                response_deserializer=gough_dot_ipxe__pb2.FetchCloudInitResponse.FromString,
                _registered_method=True)


class IPXEServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResolveBootScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindMac(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MintBootstrapToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchCloudInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IPXEServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveBootScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveBootScript,
                    request_deserializer=gough_dot_ipxe__pb2.ResolveBootScriptRequest.FromString,
                    response_serializer=gough_dot_ipxe__pb2.ResolveBootScriptResponse.SerializeToString,
            ),
            'BindMac': grpc.unary_unary_rpc_method_handler(
                    servicer.BindMac,
                    request_deserializer=gough_dot_ipxe__pb2.BindMacRequest.FromString,
                    response_serializer=gough_dot_ipxe__pb2.BindMacResponse.SerializeToString,
            ),
            'MintBootstrapToken': grpc.unary_unary_rpc_method_handler(
                    servicer.MintBootstrapToken,
                    request_deserializer=gough_dot_ipxe__pb2.MintBootstrapTokenRequest.FromString,
                    response_serializer=gough_dot_ipxe__pb2.MintBootstrapTokenResponse.SerializeToString,
            ),
            'FetchCloudInit': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchCloudInit,
                    request_deserializer=gough_dot_ipxe__pb2.FetchCloudInitRequest.FromString,
                    response_serializer=gough_dot_ipxe__pb2.FetchCloudInitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gough.v1.IPXE', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gough.v1.IPXE', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IPXE(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveBootScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.IPXE/ResolveBootScript',
            gough_dot_ipxe__pb2.ResolveBootScriptRequest.SerializeToString,
            gough_dot_ipxe__pb2.ResolveBootScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindMac(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.IPXE/BindMac',
            gough_dot_ipxe__pb2.BindMacRequest.SerializeToString,
            gough_dot_ipxe__pb2.BindMacResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MintBootstrapToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.IPXE/MintBootstrapToken',
            gough_dot_ipxe__pb2.MintBootstrapTokenRequest.SerializeToString,
            gough_dot_ipxe__pb2.MintBootstrapTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchCloudInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.IPXE/FetchCloudInit',
            gough_dot_ipxe__pb2.FetchCloudInitRequest.SerializeToString,
            gough_dot_ipxe__pb2.FetchCloudInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
