# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gough/ipxe.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'gough/ipxe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10gough/ipxe.proto\x12\x08gough.v1\"T\n\x18ResolveBootScriptRequest\x12\x1f\n\x0bmac_address\x18\x01 \x01(\tR\nmacAddress\x12\x17\n\x07node_id\x18\x02 \x01(\x03R\x06nodeId\"<\n\x19ResolveBootScriptResponse\x12\x1f\n\x0b\x62oot_script\x18\x01 \x01(\tR\nbootScript\"J\n\x0e\x42indMacRequest\x12\x1f\n\x0bmac_address\x18\x01 \x01(\tR\nmacAddress\x12\x17\n\x07node_id\x18\x02 \x01(\x03R\x06nodeId\"@\n\x0f\x42indMacResponse\x12\x14\n\x05\x62ound\x18\x01 \x01(\x08R\x05\x62ound\x12\x17\n\x07node_id\x18\x02 \x01(\tR\x06nodeId\"V\n\x19MintBootstrapTokenRequest\x12\x17\n\x07node_id\x18\x01 \x01(\x03R\x06nodeId\x12 \n\x0bpermissions\x18\x02 \x03(\tR\x0bpermissions\"R\n\x1aMintBootstrapTokenResponse\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\x12\x1e\n\nexpiration\x18\x02 \x01(\x03R\nexpiration\"L\n\x15\x46\x65tchCloudInitRequest\x12\x17\n\x07node_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1a\n\x08\x62\x61seline\x18\x02 \x01(\tR\x08\x62\x61seline\"X\n\x16\x46\x65tchCloudInitResponse\x12\x1b\n\tuser_data\x18\x01 \x01(\tR\x08userData\x12!\n\x0c\x63ontent_type\x18\x02 \x01(\tR\x0b\x63ontentType2\xda\x02\n\x04IPXE\x12\\\n\x11ResolveBootScript\x12\".gough.v1.ResolveBootScriptRequest\x1a#.gough.v1.ResolveBootScriptResponse\x12>\n\x07\x42indMac\x12\x18.gough.v1.BindMacRequest\x1a\x19.gough.v1.BindMacResponse\x12_\n\x12MintBootstrapToken\x12#.gough.v1.MintBootstrapTokenRequest\x1a$.gough.v1.MintBootstrapTokenResponse\x12S\n\x0e\x46\x65tchCloudInit\x12\x1f.gough.v1.FetchCloudInitRequest\x1a .gough.v1.FetchCloudInitResponseBTZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gough.ipxe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1'
  _globals['_RESOLVEBOOTSCRIPTREQUEST']._serialized_start=30
  _globals['_RESOLVEBOOTSCRIPTREQUEST']._serialized_end=114
  _globals['_RESOLVEBOOTSCRIPTRESPONSE']._serialized_start=116
  _globals['_RESOLVEBOOTSCRIPTRESPONSE']._serialized_end=176
  _globals['_BINDMACREQUEST']._serialized_start=178
  _globals['_BINDMACREQUEST']._serialized_end=252
  _globals['_BINDMACRESPONSE']._serialized_start=254
  _globals['_BINDMACRESPONSE']._serialized_end=318
  _globals['_MINTBOOTSTRAPTOKENREQUEST']._serialized_start=320
  _globals['_MINTBOOTSTRAPTOKENREQUEST']._serialized_end=406
  _globals['_MINTBOOTSTRAPTOKENRESPONSE']._serialized_start=408
  _globals['_MINTBOOTSTRAPTOKENRESPONSE']._serialized_end=490
  _globals['_FETCHCLOUDINITREQUEST']._serialized_start=492
  _globals['_FETCHCLOUDINITREQUEST']._serialized_end=568
  _globals['_FETCHCLOUDINITRESPONSE']._serialized_start=570
  _globals['_FETCHCLOUDINITRESPONSE']._serialized_end=658
  _globals['_IPXE']._serialized_start=661
  _globals['_IPXE']._serialized_end=1007
# @@protoc_insertion_point(module_scope)
