# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gough import network_pb2 as gough_dot_network__pb2


class NetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BaselineConfigure = channel.unary_unary(
                '/gough.v1.Network/BaselineConfigure',
                request_serializer=gough_dot_network__pb2.BaselineConfigureRequest.SerializeToString,
                response_deserializer=gough_dot_network__pb2.BaselineConfigureResponse.FromString,
                _registered_method=True)
        self.ProviderMigrate = channel.unary_unary(
                '/gough.v1.Network/ProviderMigrate',
                request_serializer=gough_dot_network__pb2.ProviderMigrateRequest.SerializeToString,
                response_deserializer=gough_dot_network__pb2.ProviderMigrateResponse.FromString,
                _registered_method=True)
        self.FallbackControl = channel.unary_unary(
                '/gough.v1.Network/FallbackControl',
                request_serializer=gough_dot_network__pb2.FallbackControlRequest.SerializeToString,
                response_deserializer=gough_dot_network__pb2.FallbackControlResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/gough.v1.Network/Status',
                request_serializer=gough_dot_network__pb2.NetworkStatusRequest.SerializeToString,
                response_deserializer=gough_dot_network__pb2.NetworkStatusResponse.FromString,
                _registered_method=True)


class NetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BaselineConfigure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProviderMigrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FallbackControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BaselineConfigure': grpc.unary_unary_rpc_method_handler(
                    servicer.BaselineConfigure,
                    request_deserializer=gough_dot_network__pb2.BaselineConfigureRequest.FromString,
                    response_serializer=gough_dot_network__pb2.BaselineConfigureResponse.SerializeToString,
            ),
            'ProviderMigrate': grpc.unary_unary_rpc_method_handler(
                    servicer.ProviderMigrate,
                    request_deserializer=gough_dot_network__pb2.ProviderMigrateRequest.FromString,
                    response_serializer=gough_dot_network__pb2.ProviderMigrateResponse.SerializeToString,
            ),
            'FallbackControl': grpc.unary_unary_rpc_method_handler(
                    servicer.FallbackControl,
                    request_deserializer=gough_dot_network__pb2.FallbackControlRequest.FromString,
                    response_serializer=gough_dot_network__pb2.FallbackControlResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=gough_dot_network__pb2.NetworkStatusRequest.FromString,
                    response_serializer=gough_dot_network__pb2.NetworkStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gough.v1.Network', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gough.v1.Network', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Network(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BaselineConfigure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Network/BaselineConfigure',
            gough_dot_network__pb2.BaselineConfigureRequest.SerializeToString,
            gough_dot_network__pb2.BaselineConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProviderMigrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Network/ProviderMigrate',
            gough_dot_network__pb2.ProviderMigrateRequest.SerializeToString,
            gough_dot_network__pb2.ProviderMigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FallbackControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Network/FallbackControl',
            gough_dot_network__pb2.FallbackControlRequest.SerializeToString,
            gough_dot_network__pb2.FallbackControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Network/Status',
            gough_dot_network__pb2.NetworkStatusRequest.SerializeToString,
            gough_dot_network__pb2.NetworkStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
