# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gough import nodes_pb2 as gough_dot_nodes__pb2


class NodesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/gough.v1.Nodes/Discover',
                request_serializer=gough_dot_nodes__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/gough.v1.Nodes/List',
                request_serializer=gough_dot_nodes__pb2.ListRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/gough.v1.Nodes/Get',
                request_serializer=gough_dot_nodes__pb2.GetRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Patch = channel.unary_unary(
                '/gough.v1.Nodes/Patch',
                request_serializer=gough_dot_nodes__pb2.PatchRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.PatchResponse.FromString,
                _registered_method=True)
        self.Deploy = channel.unary_unary(
                '/gough.v1.Nodes/Deploy',
                request_serializer=gough_dot_nodes__pb2.DeployRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.Reject = channel.unary_unary(
                '/gough.v1.Nodes/Reject',
                request_serializer=gough_dot_nodes__pb2.RejectRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.RejectResponse.FromString,
                _registered_method=True)
        self.Rekey = channel.unary_unary(
                '/gough.v1.Nodes/Rekey',
                request_serializer=gough_dot_nodes__pb2.RekeyRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.RekeyResponse.FromString,
                _registered_method=True)
        self.Evacuate = channel.unary_unary(
                '/gough.v1.Nodes/Evacuate',
                request_serializer=gough_dot_nodes__pb2.EvacuateRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.EvacuateResponse.FromString,
                _registered_method=True)
        self.Decommission = channel.unary_unary(
                '/gough.v1.Nodes/Decommission',
                request_serializer=gough_dot_nodes__pb2.DecommissionRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.DecommissionResponse.FromString,
                _registered_method=True)
        self.EventStream = channel.unary_stream(
                '/gough.v1.Nodes/EventStream',
                request_serializer=gough_dot_nodes__pb2.EventStreamRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.EventStreamResponse.FromString,
                _registered_method=True)
        self.AddManual = channel.unary_unary(
                '/gough.v1.Nodes/AddManual',
                request_serializer=gough_dot_nodes__pb2.AddManualRequest.SerializeToString,
                response_deserializer=gough_dot_nodes__pb2.AddManualResponse.FromString,
                _registered_method=True)


class NodesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Patch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deploy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rekey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evacuate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decommission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddManual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=gough_dot_nodes__pb2.DiscoverRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.DiscoverResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=gough_dot_nodes__pb2.ListRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.ListResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=gough_dot_nodes__pb2.GetRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.GetResponse.SerializeToString,
            ),
            'Patch': grpc.unary_unary_rpc_method_handler(
                    servicer.Patch,
                    request_deserializer=gough_dot_nodes__pb2.PatchRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.PatchResponse.SerializeToString,
            ),
            'Deploy': grpc.unary_unary_rpc_method_handler(
                    servicer.Deploy,
                    request_deserializer=gough_dot_nodes__pb2.DeployRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.DeployResponse.SerializeToString,
            ),
            'Reject': grpc.unary_unary_rpc_method_handler(
                    servicer.Reject,
                    request_deserializer=gough_dot_nodes__pb2.RejectRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.RejectResponse.SerializeToString,
            ),
            'Rekey': grpc.unary_unary_rpc_method_handler(
                    servicer.Rekey,
                    request_deserializer=gough_dot_nodes__pb2.RekeyRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.RekeyResponse.SerializeToString,
            ),
            'Evacuate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evacuate,
                    request_deserializer=gough_dot_nodes__pb2.EvacuateRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.EvacuateResponse.SerializeToString,
            ),
            'Decommission': grpc.unary_unary_rpc_method_handler(
                    servicer.Decommission,
                    request_deserializer=gough_dot_nodes__pb2.DecommissionRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.DecommissionResponse.SerializeToString,
            ),
            'EventStream': grpc.unary_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=gough_dot_nodes__pb2.EventStreamRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.EventStreamResponse.SerializeToString,
            ),
            'AddManual': grpc.unary_unary_rpc_method_handler(
                    servicer.AddManual,
                    request_deserializer=gough_dot_nodes__pb2.AddManualRequest.FromString,
                    response_serializer=gough_dot_nodes__pb2.AddManualResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gough.v1.Nodes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gough.v1.Nodes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Nodes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Discover',
            gough_dot_nodes__pb2.DiscoverRequest.SerializeToString,
            gough_dot_nodes__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/List',
            gough_dot_nodes__pb2.ListRequest.SerializeToString,
            gough_dot_nodes__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Get',
            gough_dot_nodes__pb2.GetRequest.SerializeToString,
            gough_dot_nodes__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Patch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Patch',
            gough_dot_nodes__pb2.PatchRequest.SerializeToString,
            gough_dot_nodes__pb2.PatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deploy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Deploy',
            gough_dot_nodes__pb2.DeployRequest.SerializeToString,
            gough_dot_nodes__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Reject',
            gough_dot_nodes__pb2.RejectRequest.SerializeToString,
            gough_dot_nodes__pb2.RejectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rekey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Rekey',
            gough_dot_nodes__pb2.RekeyRequest.SerializeToString,
            gough_dot_nodes__pb2.RekeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evacuate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Evacuate',
            gough_dot_nodes__pb2.EvacuateRequest.SerializeToString,
            gough_dot_nodes__pb2.EvacuateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decommission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/Decommission',
            gough_dot_nodes__pb2.DecommissionRequest.SerializeToString,
            gough_dot_nodes__pb2.DecommissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gough.v1.Nodes/EventStream',
            gough_dot_nodes__pb2.EventStreamRequest.SerializeToString,
            gough_dot_nodes__pb2.EventStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddManual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Nodes/AddManual',
            gough_dot_nodes__pb2.AddManualRequest.SerializeToString,
            gough_dot_nodes__pb2.AddManualResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
