# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gough import primary_pb2 as gough_dot_primary__pb2


class PrimaryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/gough.v1.Primary/Status',
                request_serializer=gough_dot_primary__pb2.PrimaryStatusRequest.SerializeToString,
                response_deserializer=gough_dot_primary__pb2.PrimaryStatusResponse.FromString,
                _registered_method=True)
        self.Replace = channel.unary_unary(
                '/gough.v1.Primary/Replace',
                request_serializer=gough_dot_primary__pb2.ReplaceRequest.SerializeToString,
                response_deserializer=gough_dot_primary__pb2.ReplaceResponse.FromString,
                _registered_method=True)
        self.ForceRecover = channel.unary_unary(
                '/gough.v1.Primary/ForceRecover',
                request_serializer=gough_dot_primary__pb2.ForceRecoverRequest.SerializeToString,
                response_deserializer=gough_dot_primary__pb2.ForceRecoverResponse.FromString,
                _registered_method=True)
        self.FrontendSwitch = channel.unary_unary(
                '/gough.v1.Primary/FrontendSwitch',
                request_serializer=gough_dot_primary__pb2.FrontendSwitchRequest.SerializeToString,
                response_deserializer=gough_dot_primary__pb2.FrontendSwitchResponse.FromString,
                _registered_method=True)
        self.RotateCA = channel.unary_unary(
                '/gough.v1.Primary/RotateCA',
                request_serializer=gough_dot_primary__pb2.RotateCARequest.SerializeToString,
                response_deserializer=gough_dot_primary__pb2.RotateCAResponse.FromString,
                _registered_method=True)


class PrimaryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceRecover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FrontendSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateCA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimaryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=gough_dot_primary__pb2.PrimaryStatusRequest.FromString,
                    response_serializer=gough_dot_primary__pb2.PrimaryStatusResponse.SerializeToString,
            ),
            'Replace': grpc.unary_unary_rpc_method_handler(
                    servicer.Replace,
                    request_deserializer=gough_dot_primary__pb2.ReplaceRequest.FromString,
                    response_serializer=gough_dot_primary__pb2.ReplaceResponse.SerializeToString,
            ),
            'ForceRecover': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceRecover,
                    request_deserializer=gough_dot_primary__pb2.ForceRecoverRequest.FromString,
                    response_serializer=gough_dot_primary__pb2.ForceRecoverResponse.SerializeToString,
            ),
            'FrontendSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.FrontendSwitch,
                    request_deserializer=gough_dot_primary__pb2.FrontendSwitchRequest.FromString,
                    response_serializer=gough_dot_primary__pb2.FrontendSwitchResponse.SerializeToString,
            ),
            'RotateCA': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateCA,
                    request_deserializer=gough_dot_primary__pb2.RotateCARequest.FromString,
                    response_serializer=gough_dot_primary__pb2.RotateCAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gough.v1.Primary', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gough.v1.Primary', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Primary(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Primary/Status',
            gough_dot_primary__pb2.PrimaryStatusRequest.SerializeToString,
            gough_dot_primary__pb2.PrimaryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Primary/Replace',
            gough_dot_primary__pb2.ReplaceRequest.SerializeToString,
            gough_dot_primary__pb2.ReplaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceRecover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Primary/ForceRecover',
            gough_dot_primary__pb2.ForceRecoverRequest.SerializeToString,
            gough_dot_primary__pb2.ForceRecoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FrontendSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Primary/FrontendSwitch',
            gough_dot_primary__pb2.FrontendSwitchRequest.SerializeToString,
            gough_dot_primary__pb2.FrontendSwitchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateCA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gough.v1.Primary/RotateCA',
            gough_dot_primary__pb2.RotateCARequest.SerializeToString,
            gough_dot_primary__pb2.RotateCAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
