# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gough/primary.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'gough/primary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gough/primary.proto\x12\x08gough.v1\"/\n\x14PrimaryStatusRequest\x12\x17\n\x07node_id\x18\x01 \x01(\tR\x06nodeId\"`\n\x15PrimaryStatusResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n\tleader_id\x18\x02 \x01(\tR\x08leaderId\x12\x12\n\x04term\x18\x03 \x01(\x03R\x04term\"?\n\x0eReplaceRequest\x12-\n\x12replacement_config\x18\x01 \x01(\tR\x11replacementConfig\")\n\x0fReplaceResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\">\n\x13\x46orceRecoverRequest\x12\'\n\x0frecovery_params\x18\x01 \x01(\tR\x0erecoveryParams\".\n\x14\x46orceRecoverResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\"@\n\x15\x46rontendSwitchRequest\x12\'\n\x0ftarget_frontend\x18\x01 \x01(\tR\x0etargetFrontend\"0\n\x16\x46rontendSwitchResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\":\n\x0fRotateCARequest\x12\'\n\x0frotation_params\x18\x01 \x01(\tR\x0erotationParams\"2\n\x10RotateCAResponse\x12\x1e\n\x0bnew_ca_cert\x18\x01 \x01(\tR\tnewCaCert2\xfb\x02\n\x07Primary\x12I\n\x06Status\x12\x1e.gough.v1.PrimaryStatusRequest\x1a\x1f.gough.v1.PrimaryStatusResponse\x12>\n\x07Replace\x12\x18.gough.v1.ReplaceRequest\x1a\x19.gough.v1.ReplaceResponse\x12M\n\x0c\x46orceRecover\x12\x1d.gough.v1.ForceRecoverRequest\x1a\x1e.gough.v1.ForceRecoverResponse\x12S\n\x0e\x46rontendSwitch\x12\x1f.gough.v1.FrontendSwitchRequest\x1a .gough.v1.FrontendSwitchResponse\x12\x41\n\x08RotateCA\x12\x19.gough.v1.RotateCARequest\x1a\x1a.gough.v1.RotateCAResponseBTZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gough.primary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/penguintechinc/gough/services/discovery-agent/internal/grpcgen/gough/v1'
  _globals['_PRIMARYSTATUSREQUEST']._serialized_start=33
  _globals['_PRIMARYSTATUSREQUEST']._serialized_end=80
  _globals['_PRIMARYSTATUSRESPONSE']._serialized_start=82
  _globals['_PRIMARYSTATUSRESPONSE']._serialized_end=178
  _globals['_REPLACEREQUEST']._serialized_start=180
  _globals['_REPLACEREQUEST']._serialized_end=243
  _globals['_REPLACERESPONSE']._serialized_start=245
  _globals['_REPLACERESPONSE']._serialized_end=286
  _globals['_FORCERECOVERREQUEST']._serialized_start=288
  _globals['_FORCERECOVERREQUEST']._serialized_end=350
  _globals['_FORCERECOVERRESPONSE']._serialized_start=352
  _globals['_FORCERECOVERRESPONSE']._serialized_end=398
  _globals['_FRONTENDSWITCHREQUEST']._serialized_start=400
  _globals['_FRONTENDSWITCHREQUEST']._serialized_end=464
  _globals['_FRONTENDSWITCHRESPONSE']._serialized_start=466
  _globals['_FRONTENDSWITCHRESPONSE']._serialized_end=514
  _globals['_ROTATECAREQUEST']._serialized_start=516
  _globals['_ROTATECAREQUEST']._serialized_end=574
  _globals['_ROTATECARESPONSE']._serialized_start=576
  _globals['_ROTATECARESPONSE']._serialized_end=626
  _globals['_PRIMARY']._serialized_start=629
  _globals['_PRIMARY']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
